---
# vim: set softtabstop=2 tabstop=2 shiftwidth=2 expandtab autoindent smartindent syntax=yaml:

# SELinux disrupts LXC (shrug)

- name: Disable SELinux for Docker Driver
  selinux:
    state: disabled
  when: nomad_docker_enable == "true"
