---
# vim: set softtabstop=2 tabstop=2 shiftwidth=2 expandtab autoindent smartindent syntax=yaml:

- name: Installing Nomad
  hosts: nomad_instances
  become: yes
  become_user: root
  roles:
    - { role: brianshumate.nomad }

  tasks:
    - name: Start nomad
      service: name=nomad state=started enabled=yes
